---
- name: Fetch file1 from server1 to server2
  hosts: 172.31.36.96
  tasks:
    - name: Fetch file
      fetch:
        src: file2
        dest: /tmp
- name: copy file into server2
  hosts: 172.31.36.3
  tasks:
    - name: Copy file into server2
      copy:
        src: /tmp/172.31.36.96/file2
        dest: /tmp
...



