---
- name: create user on all server
  hosts: servers
  tasks:
    - name: user creation
      user:
        name: ravi
        password: admin
        uid: 222
        shell: /bin/bash
        comment: "a normal user"
        home: /tmp/ravi
...
