---
- name: Create users and files/dir in remote server
  hosts: all
  tasks:
    - name: Create users
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: Create files/dir
      file:
        name: "{{d}}"
        state: "{{e}}"
...




