
---
- name: Configure apache/httpd
  hosts: all
  tasks:
    - name: Install apache2 using apt
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install httpd using yum
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: Edit the index.hmtl file
      copy:
        content: "Welcome to Intelliq"
        dest: /var/www/html/index.html
    - name: restart apache2 on ubuntu server
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
    - name: Restart httpd on RHEL servers
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"
    - name: Check apache2/httpd response on all server
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.36.96
        - http://172.31.36.3
        - http://172.31.6.164
        - http://172.31.36.170
...
