---
- name: Create 10 nginx container
  hosts: all
  tasks: 
    - name: Create nginx container
      docker_container: 
        name: "container{{item}}"
        image: nginx
        with_sequence: count=10 
