---
- name: Working on a docker container
  hosts: all
  tasks:
    - name: Create a tomcat container
      docker_container:
        name: apiserver
        image: tomee
    - name: Stoped tomcat cantainer
      docker_container:
        name: apiserver
        state: stopped
    - name: Delete the tomcat container
      docker_container:
        name: apiserver
        state: absent 


