---
- name: Create users and copy files into home dir
  hosts: all
  tasks:
    - name: Create users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: raju,b: intelliqit,c: /home/raju}
        - {a: ravi,b: intelliqit,c: /home/ravi}
    - name: Copy files into users home dir
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd,b: /home/raju}
        - {a: /etc/passwd,b: /home/ravi}
...




